// <auto-generated />
using System;
using API_NFC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API___NFC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215160625_InicialPostgres")]
    partial class InicialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API___NFC.Models.Aprendiz", b =>
                {
                    b.Property<int>("IdAprendiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAprendiz"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdFicha")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("IdAprendiz");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdFicha");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Aprendiz", t =>
                        {
                            t.HasCheckConstraint("CHK_Aprendiz_TipoDocumento", "(\"TipoDocumento\"='PA' OR \"TipoDocumento\"='CE' OR \"TipoDocumento\"='TI' OR \"TipoDocumento\"='CC')");
                        });
                });

            modelBuilder.Entity("API___NFC.Models.DetalleRegistroNFC", b =>
                {
                    b.Property<int>("IdDetalleRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleRegistro"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdElemento")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("IdRegistroNFC")
                        .HasColumnType("integer");

                    b.Property<bool?>("Validado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("IdDetalleRegistro");

                    b.HasIndex("IdElemento");

                    b.HasIndex("IdProceso");

                    b.HasIndex("IdRegistroNFC");

                    b.ToTable("DetalleRegistroNFC", t =>
                        {
                            t.HasCheckConstraint("CHK_DetalleRegistroNFC_Accion", "(\"Accion\"='Ingreso' OR \"Accion\"='Salida' OR \"Accion\"='Quedo')");
                        });
                });

            modelBuilder.Entity("API___NFC.Models.Elemento", b =>
                {
                    b.Property<int>("IdElemento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdElemento"));

                    b.Property<string>("CodigoNFC")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoElemento")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoPropietario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdElemento");

                    b.HasIndex("CodigoNFC")
                        .IsUnique();

                    b.HasIndex("IdTipoElemento");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("Elemento", t =>
                        {
                            t.HasCheckConstraint("CHK_Elemento_TipoPropietario", "(\"TipoPropietario\"='Usuario' OR \"TipoPropietario\"='Aprendiz')");
                        });
                });

            modelBuilder.Entity("API___NFC.Models.ElementoProceso", b =>
                {
                    b.Property<int>("IdElementoProceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdElementoProceso"));

                    b.Property<int>("IdElemento")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<bool>("QuedoEnSena")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Validado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("IdElementoProceso");

                    b.HasIndex("IdElemento");

                    b.HasIndex("IdProceso");

                    b.ToTable("ElementoProceso");
                });

            modelBuilder.Entity("API___NFC.Models.Ficha", b =>
                {
                    b.Property<int>("IdFicha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFicha"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPrograma")
                        .HasColumnType("integer");

                    b.HasKey("IdFicha");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdPrograma");

                    b.ToTable("Ficha", (string)null);
                });

            modelBuilder.Entity("API___NFC.Models.Proceso", b =>
                {
                    b.Property<int>("IdProceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProceso"));

                    b.Property<string>("EstadoProceso")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("IdAprendiz")
                        .HasColumnType("integer");

                    b.Property<int>("IdGuardia")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProceso_Relacionado")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoProceso")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<bool?>("RequiereOtrosProcesos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("SincronizadoBD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("TimeStampEntradaSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdProceso");

                    b.HasIndex("IdAprendiz");

                    b.HasIndex("IdTipoProceso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Proceso", t =>
                        {
                            t.HasCheckConstraint("CHK_Proceso_TipoPersona", "(\"TipoPersona\"='Usuario' OR \"TipoPersona\"='Aprendiz')");
                        });
                });

            modelBuilder.Entity("API___NFC.Models.Programa", b =>
                {
                    b.Property<int>("IdPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrograma"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NivelFormacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NombrePrograma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdPrograma");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Programa", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Programa_NivelFormacion", "(\"NivelFormacion\"='Operario' OR \"NivelFormacion\"='Especialización' OR \"NivelFormacion\"='Tecnólogo' OR \"NivelFormacion\"='Técnico')");
                        });
                });

            modelBuilder.Entity("API___NFC.Models.RegistroNFC", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegistro"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("IdAprendiz")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdAprendiz");

                    b.HasIndex("IdProceso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RegistroNFC");
                });

            modelBuilder.Entity("API___NFC.Models.TagAsignado", b =>
                {
                    b.Property<int>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTag"));

                    b.Property<string>("CodigoTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdTag");

                    b.ToTable("TagAsignado");
                });

            modelBuilder.Entity("API___NFC.Models.TipoElemento", b =>
                {
                    b.Property<int>("IdTipoElemento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoElemento"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("RequiereNFC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdTipoElemento");

                    b.HasIndex("Tipo")
                        .IsUnique();

                    b.ToTable("TipoElemento");
                });

            modelBuilder.Entity("API___NFC.Models.TipoProceso", b =>
                {
                    b.Property<int>("IdTipoProceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoProceso"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdTipoProceso");

                    b.HasIndex("Tipo")
                        .IsUnique();

                    b.ToTable("TipoProceso");
                });

            modelBuilder.Entity("API___NFC.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaTokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Usuario_Rol", "(\"Rol\"='Administrador' OR \"Rol\"='Guardia' OR \"Rol\"='Funcionario')");

                            t.HasCheckConstraint("CHK_Usuario_TipoDocumento", "(\"TipoDocumento\"='PA' OR \"TipoDocumento\"='CE' OR \"TipoDocumento\"='TI' OR \"TipoDocumento\"='CC')");
                        });
                });

            modelBuilder.Entity("API___NFC.Models.Aprendiz", b =>
                {
                    b.HasOne("API___NFC.Models.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("IdFicha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("API___NFC.Models.DetalleRegistroNFC", b =>
                {
                    b.HasOne("API___NFC.Models.Elemento", "Elemento")
                        .WithMany()
                        .HasForeignKey("IdElemento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API___NFC.Models.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API___NFC.Models.RegistroNFC", "RegistroNFC")
                        .WithMany("Detalles")
                        .HasForeignKey("IdRegistroNFC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elemento");

                    b.Navigation("Proceso");

                    b.Navigation("RegistroNFC");
                });

            modelBuilder.Entity("API___NFC.Models.Elemento", b =>
                {
                    b.HasOne("API___NFC.Models.TipoElemento", "TipoElemento")
                        .WithMany()
                        .HasForeignKey("IdTipoElemento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoElemento");
                });

            modelBuilder.Entity("API___NFC.Models.ElementoProceso", b =>
                {
                    b.HasOne("API___NFC.Models.Elemento", "Elemento")
                        .WithMany()
                        .HasForeignKey("IdElemento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API___NFC.Models.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elemento");

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("API___NFC.Models.Ficha", b =>
                {
                    b.HasOne("API___NFC.Models.Programa", "Programa")
                        .WithMany("Fichas")
                        .HasForeignKey("IdPrograma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("API___NFC.Models.Proceso", b =>
                {
                    b.HasOne("API___NFC.Models.Aprendiz", "Aprendiz")
                        .WithMany()
                        .HasForeignKey("IdAprendiz")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API___NFC.Models.TipoProceso", "TipoProceso")
                        .WithMany()
                        .HasForeignKey("IdTipoProceso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API___NFC.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aprendiz");

                    b.Navigation("TipoProceso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API___NFC.Models.RegistroNFC", b =>
                {
                    b.HasOne("API___NFC.Models.Aprendiz", "Aprendiz")
                        .WithMany()
                        .HasForeignKey("IdAprendiz")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API___NFC.Models.Proceso", "Proceso")
                        .WithMany()
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API___NFC.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aprendiz");

                    b.Navigation("Proceso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API___NFC.Models.Programa", b =>
                {
                    b.Navigation("Fichas");
                });

            modelBuilder.Entity("API___NFC.Models.RegistroNFC", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
